// <auto-generated />
namespace Bazy_danych.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.2")]
    public sealed partial class DodanieTabeliSerwisu1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DodanieTabeliSerwisu1));
        
        string IMigrationMetadata.Id
        {
            get { return "202606180011318_DodanieTabeliSerwisu1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
